name: LIMA Qcow2

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ✅ Step 1: Authenticate to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    # ✅ Step 2: Set up gcloud SDK
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: 'heidelberg-417321'
        install_components: 'gsutil'

    # ✅ Step 3: Confirm authenticated identity
    - name: Who am I
      run: gcloud auth list

    - name: Run QCOW2 creation script
      run: |
        touch image.qcow2
        gsutil cp image.qcow2 gs://${{ secrets.GCP_BUCKET }}/${{ secrets.IMAGE_NAME }}

    - name: Output public URL
      run: echo "QCOW2 uploaded to https://storage.googleapis.com/lima-images-qcow2/garden-lima-today.qcow2"

