name: LIMA Qcow2

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # ✅ Step 1: Authenticate to GCP
    - name: Authenticate to GCloud via OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        create_credentials_file: true
        export_environment_variables: true

    ## ✅ Step 2: Set up gcloud SDK  
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        install_components: 'gsutil'

    # ✅ Step 3: Confirm authenticated identity
    - name: Check myself once
      run: gcloud auth list

    - name: AMD64
      run: |
        ./build kvm-lima-amd64
        cd ./.build
        IMAGE_AMD=$(find . -mmin -20 -maxdepth 1 -type f -name "*amd*.qcow2" -exec basename {} \;)
        gsutil cp "${IMAGE_AMD}" gs://${{ secrets.GCP_BUCKET }}/gardenlinux-amd64-today.qcow2

    - name: ARM64
      run: |
        sudo apt-get update
        sudo apt-get install -y ovmf qemu-efi-aarch64 qemu-user-static binfmt-support
        sudo update-binfmts --enable qemu-aarch64
        ./build kvm-lima-arm64      
        cd ./.build
        IMAGE_ARM=$(find . -mmin -20 -maxdepth 1 -type f -name "*arm*.qcow2" -exec basename {} \;)
        gsutil cp "${IMAGE_ARM}" gs://${{ secrets.GCP_BUCKET }}/gardenlinux-arm64-today.qcow2
    
    # ✅ Step 5: Confirmation with URL
    - name: Output public URL
      run: echo "QCOW2 uploaded to https://storage.googleapis.com/lima-images-qcow2/garden-lima-today.qcow2"
