name: LIMA Qcow2

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: 'heidelberg-417321'
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true

    - name: Run QCOW2 creation script
      run: |
        ./build kvm-lima-amd64
        cd ./.build
        IMAGE_QCOW2=$(find . -mmin -20 -maxdepth 1 -type f -name "*.qcow2" -exec basename {} \;)
        gsutil cp "${IMAGE_QCOW2}" gs://${{ secrets.GCP_BUCKET }}/${{ secrets.IMAGE_NAME }}

    - name: Output public URL
      run: echo "QCOW2 uploaded to https://storage.googleapis.com/lima-images-qcow2/garden-lima-today.qcow2"

