name: LIMA Qcow2

on:
  push:
    branches:
      - lima-upload
  schedule:
    - cron: '0 11 * * 2'  # Every Tuesday at 11:00
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: AMD64
      run: |
        mkdir -p output
        cd output
        touch kvm-amd64-today.qcow2
        touch sha512-amd64-today.sha512
        

    - name: ARM64
      run: |
        mkdir -p output
        cd output
        touch kvm-arm64-today.qcow2
        touch sha512-arm64-today.sha512

    - name: lima.yaml
      run: |
        mkdir -p output
        cd output
        SHA_AMD=$(cat "*amd*".sha512)
        SHA_ARM=$(cat "*arm*".sha512)
        cat <<EOF > lima.yaml
        vmType: qemu
        os: Linux
        images:
        - location: "https://images.gardenlinux.io/gardenlinux-amd64-today.qcow2"
          arch: "x86_64"
          digest: "sha512:${SHA_AMD}"
        - location: "https://images.gardenlinux.io/gardenlinux-arm64-today.qcow2"
          arch: "aarch64"
          digest: "sha512:${SHA_ARM}"

        containerd:
          system: false
          user: false
        EOF
        ls -l .
        cat lima.yaml
#    - name: Authenticate to GCloud via OIDC
#      uses: google-github-actions/auth@v2
#      with:
#        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
#        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
#        create_credentials_file: true
#        export_environment_variables: true

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}


    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: '${{ secrets.GCP_PROJECT }}'
        install_components: 'gsutil'


    - name: Upload image and checksum to GCS
      run: |
        cd output
        gsutil cp "lima.yaml" gs://${{ secrets.GCP_BUCKET }}/lima.yaml

